#####################################################
global:
  # Set to true if user need to access Spinnaker seperately
  spinnakerUrl: false
  ## URL that will be used to access ISD. MUST BE CHANGED
  ## Ensure that this URL is reachable from your browser. Either DNS name server record must exist or "hosts" file must be updated
  oesUI:
    protocol: http # Set to https if global.certManager and global.ssl is true
    host: ISD.REPLACE.THIS.WITH.YOURCOMPANY.COM  # Replace the ISD URL

  spinDeck:
    protocol: http # Set to https if global.certManager and global.ssl is true
    host: SPINNAKER.REPLACE.THIS.WITH.YOURCOMPANY.COM   # Replace the Spinnaker URL

  # Set to true if you are using the saml/Okta for Spinnaker
  auth:
    saml: false

  ssl:
    enabled: false # Set to true if using "httpS" urls. TLS certificates must be generated for the above URL

  certManager:
    installed: false # Set to true if you have cert-manager installed in the cluster, the URL must be accessible from the internet

  ## nginx ingress objects are created if set to true. Set to false if using LoadBalancer or any other ingress
  ## The cluster MUST have nginx ingress controller already installed
  createIngress: true

  #Only for trial purposes, pod-baesd git is installed and automatically configured
  gitea:
    enabled: false # Set to true for trial-install only

  ###############################################################################
  # A trial LDAP is installed by default, with users: admin, user1,2,3 with user1password, user2pa...
  # Set it to false if own LDAP is to be configured
  installOpenLdap: true

  ## ldap configuration used in oes-gate, oes-platform and spinnaker gate for authentication and authorization
  ldap:
    managerPassword: encrypted:ldappassword:ldappassword

   ## Valid admin details for ISD authorization
  saporgate:
    config:
      username: admin       #Name of the valid user in your service provider
      adminGroups: admin    #Name of the valid admin group in your service provider
      password: encrypted:saporpassword:saporpassword  #password for the saporgate

  minio:
    accessKey: encrypted:miniopassword:miniopassword
    secretKey: encrypted:miniopassword:miniopassword

####################################################
spinnaker:
  gitopsHalyard: # A repo with appropriate contents used for configuring Spinnaker
    repo:
      type: git # git, s3, stash(bitbucket server) use a different sample values file for s3/bitbuck-stash
      ## Git repo details, https://<baseUrlHostName>/<organization>/<repository>
      organization: YOUR_ORG_NAME_OR_YOUR_USER_NAME_IF_NO_ORG
      repository: YOUR_REPO_NAME # repo name for GitOps Halyard, will be created if "githubcreationHook" is set to true
      username: YOUR_USER_NAME  # Username to authenticate with git/stash repo
      dynamicAccRepository: SAME_AS_REPOSITORY_ABOVE # Repo name of the GitOps Dynamic Accounts Directory, Can be same as "repository"

      ########################################################################################
      ## Additional git-repo parameters, typically no need to be change
      ########################################################################################

      configArgs: "http.sslVerify=false"  # Extra arguments to the git clone command
      ## Configure below fields only if repo type is git/stash.
      baseUrlHostName: github.com    # Change only if using enterprise git or another repo-type
      projectName: ""                # Specify project name only if repo is under a project
      halConfigBranch: main        # Branch for the "repository", recommend to keep "main"
      halConfigPath: /               #relative path from repository root folder
      dynAccntConfigPath: /          #relative path from repository root folder
      token: encrypted:gittoken:gittoken  # Token corresponding to spinnaker.gitopsHalyard.repo.username

  ########################################################################################
  # Lines below this do not need to be changed except where external SSO and DBs are used
  ########################################################################################
  
  ## Here basic ldap auth is used by default; everything under spinCli will be pasted in ~/.spin/config
  spinCli:
    auth:
      basic:
        username: admin          # Use credentials corresponding to saporgate.config.username
        password: encrypted:saporpassword:saporpassword     # Use credentials corresponding to saporgate.config.password

####################################################
gate:
  config:
    #####################################################
    # SAML AUthentication
    #####################################################
    # keytool -genkey -v -keystore oessaml.jks -alias saml -keyalg RSA -keysize 2048 -validity 10000
    # oessaml.jks and oesmetadata.xml are mounted as secrets, create them as follows
    # kubectl create secret generic oesmetadataxml --from-file=oesmetadata.xml -n <namespace>
    # kubectl create secret generic oessamljks --from-file=oessaml.jks -n <namespace>
    # kubectl create secret generic samljks-password --from-literal password=changeit -n <namespace>
    saml:
      enabled: false
      userSource: gate  # Groups will be obtained from SAML
      keyStore: /opt/spinnaker/saml/oessaml.jks  # The key in this secret must be oessaml.jks
      keyStorePassword: encrypted:keystorepassword:keystorepassword
      keyStoreAliasName: saml
      metadataUrl: /opt/spinnaker/saml/oesmetadata.xml # The key in this secret must be oesmetadata.xml
      redirectProtocol: https
      redirectHostname: oes-gate.ryzon7-gitops.opsmx.org  # OES gate host name
      redirectBasePath: /
      issuerId: ryzonoesgate
      jksSecretName: oessamljks
      metadataSecretName: oesmetadataxml

#######################################################################################
# Lines below this do not need to be changed except where external Redis and DBs is used
########################################################################################
redis:
  url: redis://:encrypted:redispassword:redispassword@{{ .Release.Name }}-redis-master
  password: encrypted:redispassword:redispassword
#####################################################
db:
  url: jdbc:postgresql://oes-db:5432
  username: postgres
  password: encrypted:dbpassword:dbpassword
########################################################################################
# Do not change the below parameter leave it as it is
########################################################################################
rabbitmq:
  username: rabbitmq
  password: encrypted:rabbitmqpassword:rabbitmqpassword
#####################################################
# OpenLDAP custom configuration; will override default configuration of openldap helm chart
openldap:
  adminPassword: encrypted:ldappassword:ldappassword
  configPassword: encrypted:ldapconfigpassword:ldapconfigpassword
